// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjvtgafsuvfjguvkegpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqdnRnYWZzdXZmamd1dmtlZ3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODMyNzYsImV4cCI6MjA2NzU1OTI3Nn0.aGqqTNkvUE-5vBKbWqoQTI6pMQhIJnvlQ9O_UjPXj5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});